/**
 * Spotting generated code, because it is the contamination this tool is most vulnerable to.
 *
 * A generated file repeats itself far more than a person's code does — that is what makes
 * it generated — and repetition is the one thing this index measures. So a corpus holding
 * generated files reports a recital rate describing the generator rather than the
 * repository. The README says this about vendored directories and duplicated checkouts;
 * generated code is the same defect wearing different clothes, and it is more common
 * outside JavaScript than in it: protobuf stubs, OpenAPI clients, parser tables, ORM
 * scaffolding.
 *
 * Measured on sympy's `parsing` module, where three ANTLR-generated files sit among 52:
 * removing them moved recital from 54.1% to 51.5% and identifier accuracy from 72.8% to
 * 63.4%. Three files out of fifty-two, nine points of accuracy.
 *
 * NOTHING IS EXCLUDED BY DEFAULT. Two reasons, and both matter. This is a heuristic, and
 * a heuristic that silently dropped a third of somebody's repository would be worse than
 * the problem; and every number in this README was measured without it, so switching it
 * on by default would change what those numbers describe. The default is to COUNT and to
 * SAY SO, which is the same posture as the recital rate itself: report the thing that
 * decides whether the answer is any good, and let the reader act on it.
 */

/**
 * How much of a file to look at. Generators put their marker at the top, above or just
 * below a licence header. Reading further finds files that merely *discuss* generated
 * code — a boilerplate checker, a linter rule, this very file — and calls them generated.
 */
const HEAD_BYTES = 4096;

/** Start of line, then an optional comment leader of whatever language. */
const LEADER = "^[ \\t]*(?:\\/\\/|#|--|;|\\/\\*|\\*|<!--)?[ \\t]*";

/**
 * Markers, in the order of how much they are worth trusting.
 *
 * `Code generated ... DO NOT EDIT.` is a documented convention with a specification
 * behind it (Go's), `@generated` is the convention Meta's tooling looks for, and the rest
 * are the phrasings that generators in the wild actually emit.
 */
const HEAD_MARKERS = [
  // Go's documented convention, and the strongest signal there is.
  /^[^\n]{0,80}\bCode generated\b[^\n]{0,80}\bDO NOT EDIT\b/im,
  /@generated(?:\s|$)/m,
  // A shout on a line of its own, or at the end of a header line.
  /^[^\n]{0,80}\bDO NOT EDIT\b/im,
  /\bGenerated by the protocol buffer compiler\b/im,
  // The rest are anchored to the START of a line, after an optional comment leader,
  // because that is where a generator writes its header and prose does not. Unanchored,
  // `# A little note: they could be auto-generated by an admin` reads as generated code —
  // an ordinary comment in an ordinary Rails model, which is how this was found.
  new RegExp(`${LEADER}(?:This file (?:was |is )?(?:auto[- ]?)?generated)\\b`, "im"),
  new RegExp(`${LEADER}(?:Auto|Automatically)[- ]?generated by\\b`, "im"),
  new RegExp(`${LEADER}Generated by [\\w./-]+\\.(?:py|js|go|sh|rb|jar)\\b`, "im"),
];

/**
 * Names that are conventionally generated whatever the file says inside.
 *
 * A name-based rule is weaker than a marker and is kept to conventions that are close to
 * universal in their ecosystem: protobuf's `_pb2`/`.pb.`, minified bundles, and the
 * `.generated.`/`.designer.` infixes.
 */
const NAME_PATTERNS = [
  /\.min\.(?:js|css|mjs|cjs)$/i,
  /(?:^|[.\-_])min\.js$/i,
  /_pb2(?:_grpc)?\.pyi?$/,
  /\.pb\.(?:go|cc|h|py|rb)$/,
  /_pb\.js$/,
  /\.generated\.[A-Za-z0-9]+$/i,
  /\.designer\.cs$/i,
  /\.g\.(?:dart|cs)$/i,
  /\.freezed\.dart$/i,
];

/** Does this filename follow a convention that means "generated"? */
export function hasGeneratedName(file) {
  const base = file.replace(/^.*[\\/]/, "");
  return NAME_PATTERNS.some((re) => re.test(base));
}

/**
 * Does this file look generated?
 *
 * @param {string} text the file's contents; only the head is examined
 * @param {string} [file] the path, for the name-based conventions
 * @returns {false|"name"|"marker"} why it was flagged, so a caller can report it
 */
export function isLikelyGenerated(text, file = "") {
  if (file && hasGeneratedName(file)) return "name";
  const head = text.length > HEAD_BYTES ? text.slice(0, HEAD_BYTES) : text;
  for (const re of HEAD_MARKERS) {
    if (re.test(head)) return "marker";
  }
  return false;
}
